# automatically generated by the FlatBuffers compiler, do not modify

# namespace: ppx

import flatbuffers

class BackwardResult(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsBackwardResult(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BackwardResult()
        x.Init(buf, n + offset)
        return x

    # BackwardResult
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BackwardResult
    def GradInput(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .Tensor import Tensor
            obj = Tensor()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def BackwardResultStart(builder): builder.StartObject(1)
def BackwardResultAddGradInput(builder, gradInput): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(gradInput), 0)
def BackwardResultEnd(builder): return builder.EndObject()
