# automatically generated by the FlatBuffers compiler, do not modify

# namespace: ppx

import flatbuffers

class BatchOperation(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsBatchOperation(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BatchOperation()
        x.Init(buf, n + offset)
        return x

    # BatchOperation
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BatchOperation
    def Operations(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .Message import Message
            obj = Message()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # BatchOperation
    def OperationsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def BatchOperationStart(builder): builder.StartObject(1)
def BatchOperationAddOperations(builder, operations): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(operations), 0)
def BatchOperationStartOperationsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def BatchOperationEnd(builder): return builder.EndObject()
