# automatically generated by the FlatBuffers compiler, do not modify

# namespace: ppx

import flatbuffers

class BatchOperationResult(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsBatchOperationResult(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BatchOperationResult()
        x.Init(buf, n + offset)
        return x

    # BatchOperationResult
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BatchOperationResult
    def Results(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .Message import Message
            obj = Message()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # BatchOperationResult
    def ResultsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def BatchOperationResultStart(builder): builder.StartObject(1)
def BatchOperationResultAddResults(builder, results): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(results), 0)
def BatchOperationResultStartResultsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def BatchOperationResultEnd(builder): return builder.EndObject()
