# automatically generated by the FlatBuffers compiler, do not modify

# namespace: ppx

import flatbuffers

class Forward(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsForward(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Forward()
        x.Init(buf, n + offset)
        return x

    # Forward
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Forward
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Forward
    def Input(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .Tensor import Tensor
            obj = Tensor()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def ForwardStart(builder): builder.StartObject(2)
def ForwardAddName(builder, name): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)
def ForwardAddInput(builder, input): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(input), 0)
def ForwardEnd(builder): return builder.EndObject()
